# Generated by Django 2.0.3 on 2018-03-22 15:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_insurancetype_short_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objectgs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('defect', 'Defect Liability Period'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=60, verbose_name='Project Status'),
        ),
    ]
